NO-JIRA: ensure interface is specified for verification of old examples (there is another script!)
git-svn-id: https://svn.apache.org/repos/asf/qpid/trunk/qpid@1504524 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/cpp/examples/old_api/verify_all b/cpp/examples/old_api/verify_all
--- a/cpp/examples/old_api/verify_all
+++ b/cpp/examples/old_api/verify_all
@@ -35,7 +35,7 @@ if ! test -e "$HOME"; then
 fi
 
 trap "$qpidd -q" exit
-QPID_PORT=`$qpidd -dp0 $broker_args` || { echo "Can't run qpidd" ; exit 1; }
+QPID_PORT=`$qpidd -dp0 --interface 127.0.0.1 $broker_args` || { echo "Can't run qpidd" ; exit 1; }
 export QPID_PORT
 
 find="find $topsrcdir/cpp/examples/old_api"
