NO-JIRA: ensure interface is specified for verification of old examples
git-svn-id: https://svn.apache.org/repos/asf/qpid/trunk/qpid@1504462 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/cpp/examples/old_api/verify b/cpp/examples/old_api/verify
--- a/cpp/examples/old_api/verify
+++ b/cpp/examples/old_api/verify
@@ -113,7 +113,7 @@ remove_uuid64() {
 
 # Start private broker if QPIDD is set.
 if [ -n "$QPIDD" ] ; then
-    export QPID_PORT=`$QPIDD -dp0` || { echo "Cannot start $QPIDD" ; exit 1; }
+    export QPID_PORT=`$QPIDD -dp0 --interface 127.0.0.1` || { echo "Cannot start $QPIDD" ; exit 1; }
     trap "$QPIDD -q" EXIT
 fi
 
