Added verify scripts to run mixed python/cpp examples. bin/verify_all runs all examples.
git-svn-id: https://svn.apache.org/repos/asf/incubator/qpid/trunk/qpid@619941 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/bin/verify b/bin/verify
--- a/bin/verify
+++ b/bin/verify
@@ -38,17 +38,18 @@ background() {
 
 outputs() {
     wait 2> /dev/null		# Wait for all backgroud processes to complete
+    rm -f $script.out
     for f in "$@"; do
-	{ echo "==== $f"; eval "cat $f"; } >> verify.out || fail
+	{ echo "==== $f"; eval "cat $f"; } >> $script.out || fail
     done
 }
 
 verify() {
     FAIL=
-    dir=$1
+    if [ -d $1 ]; then dir=$1; script=verify;
+    else dir=`dirname $1`; script=`basename $1`; fi
     cd $dir || return 1
-    rm -f *.out
-    { source ./verify && diff -ac verify.out verify.in ; } || fail
+    { source ./$script && diff -ac $script.out $script.in ; } || fail
     test -z "$FAIL" && rm -f *.out
     return $FAIL
 }
@@ -67,8 +68,8 @@ if [ -n "$QPIDD" ] ; then
     trap "$QPIDD -q" EXIT
 fi
 
-for dir in "$@"; do
-    echo -n "$dir : "
-    if ( verify $dir; ) then echo "PASS";  else echo "FAIL"; RET=1; fi
+for example in "$@"; do
+    echo -n "$example : "
+    if ( verify $example; ) then echo "PASS";  else echo "FAIL"; RET=1; fi
      done
 exit $RET
