Added Ruby test infrastructure and Console tests in Ruby Fixed issues identified by the new tests:   - Improper formatting of object-id in get-query   - Remote (non-broker-resident) agents not visible to the console   - object.update() and object.merge() not implemented
git-svn-id: https://svn.apache.org/repos/asf/qpid/trunk@817312 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/qpid/cpp/bindings/qmf/tests/run_interop_tests b/qpid/cpp/bindings/qmf/tests/run_interop_tests
--- a/qpid/cpp/bindings/qmf/tests/run_interop_tests
+++ b/qpid/cpp/bindings/qmf/tests/run_interop_tests
@@ -88,9 +88,17 @@ if test -d ${PYTHON_DIR} ;  then
         echo "    Ruby agent started at pid $AGENT_PID"
         ${PYTHON_DIR}/qpid-python-test -m python_console -b localhost:$BROKER_PORT $@
         RETCODE=$?
-        stop_ruby_agent
         if test x$RETCODE != x0; then
             echo "FAIL qmf interop tests (Ruby Agent)";
+            TESTS_FAILED=1
+        fi
+
+        echo "    Ruby Agent (external storage) vs. Ruby Console"
+        ruby -I${MY_DIR} -I${MY_DIR}/../ruby -I${RUBY_LIB_DIR} ${MY_DIR}/ruby_console_test.rb localhost $BROKER_PORT $@
+        RETCODE=$?
+        stop_ruby_agent
+        if test x$RETCODE != x0; then
+            echo "FAIL qmf interop tests (Ruby Console/Ruby Agent)";
             TESTS_FAILED=1
         fi
     fi
