NO-JIRA: Control running of cluster tests.
Previously cluster tests would run if cluster services were running, even
if build was explicitly configured without CPG. Don't run cluster tests
unless the build is configured with CPG.

If the build is configured *with* CPG, you can still skip the CPG tests by setting
QPID_USE_CPG=no in the environment.

git-svn-id: https://svn.apache.org/repos/asf/qpid/trunk/qpid@1326756 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/cpp/src/tests/cpg_check.sh.in b/cpp/src/tests/cpg_check.sh.in
--- a/cpp/src/tests/cpg_check.sh.in
+++ b/cpp/src/tests/cpg_check.sh.in
@@ -7,9 +7,9 @@
 # to you under the Apache License, Version 2.0 (the
 # "License"); you may not use this file except in compliance
 # with the License.  You may obtain a copy of the License at
-# 
+#
 #   http://www.apache.org/licenses/LICENSE-2.0
-# 
+#
 # Unless required by applicable law or agreed to in writing,
 # software distributed under the License is distributed on an
 # "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
@@ -18,12 +18,16 @@
 # under the License.
 #
 
-srcdir=`dirname $0`
+QPID_USE_CPG=${QPID_USE_CPG:-@USE_CPG@}
 
-# Check AIS requirements and run tests if found.
-ps -u root | grep 'aisexec\|corosync' >/dev/null || {
-    echo WARNING: Skipping cluster tests, the aisexec or corosync daemon is not running.
-    exit 0;			# A warning, not a failure.
+# Check if CPG is enabled
+cpg_enabled() {
+    test x$QPID_USE_CPG = xyes || return 1 # disabled
+    ps -u root | grep 'aisexec\|corosync' >/dev/null || {
+	echo WARNING: Skip cluster tests, aisexec or corosync daemon is not running.
+	return 1;			# A warning, not a failure.
+    }
+    return 0
 }
 
 # Execute command with the ais group set if user is a member.
