Fix valgrind problems in VPATH builds.
git-svn-id: https://svn.eu.apache.org/repos/asf/incubator/qpid/trunk/qpid@656320 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/cpp/src/tests/python_tests b/cpp/src/tests/python_tests
--- a/cpp/src/tests/python_tests
+++ b/cpp/src/tests/python_tests
@@ -1,19 +1,17 @@
 #!/bin/sh
 # Run the python tests.
+
 QPID_PORT=${QPID_PORT:-5672}
 PYTHON_TESTS=${PYTHON_TESTS:-$*}
 MY_DIR=$(dirname $(which $0))
-PYTHON_DIR=${MY_DIR}/../../../python
+QPID_PYTHON_DIR=${QPID_PYTHON_DIR:-$MY_DIR/../../../python}
 
-run() {
+do_tests() {
     SPEC=$1
     FAILING=$2
     ./run-tests --skip-self-test -v -s $SPEC -I $FAILING -b localhost:$QPID_PORT $PYTHON_TESTS || { echo "FAIL python tests for $SPEC"; exit 1; }
 }
 
-if test -d ${PYTHON_DIR} ;  then
-    cd ${PYTHON_DIR}
-    run 0-10-errata cpp_failing_0-10.txt
-else
-    echo Warning: python tests not found.
-fi
+cd ${QPID_PYTHON_DIR} || { echo "Cannot cd ${QPID_PYTHON_DIR}"; exit 1; }
+do_tests 0-10-errata cpp_failing_0-10.txt
+
