Changed ssl_test to use 127.0.0.1 instead of hostname and to regenerate certs every time (to avoid stale certs).
git-svn-id: https://svn.apache.org/repos/asf/qpid/trunk/qpid@831846 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/cpp/src/tests/ssl_test b/cpp/src/tests/ssl_test
--- a/cpp/src/tests/ssl_test
+++ b/cpp/src/tests/ssl_test
@@ -24,10 +24,10 @@
 CONFIG=$(dirname $0)/config.null
 CERT_DIR=`pwd`/test_cert_db
 CERT_PW_FILE=`pwd`/cert.password
-HOSTNAME=`hostname`
+TEST_HOSTNAME=127.0.0.1
 COUNT=10
 
-trap stop_broker EXIT
+trap cleanup EXIT
 
 error() { echo $*; exit 1; }
 
@@ -35,11 +35,17 @@ create_certs() {
     #create certificate and key databases with single, simple, self-signed certificate in it
     mkdir ${CERT_DIR}
     certutil -N -d ${CERT_DIR} -f ${CERT_PW_FILE}
-    certutil -S -d ${CERT_DIR} -n ${HOSTNAME} -s "CN=${HOSTNAME}" -t "CT,," -x -f ${CERT_PW_FILE} -z /usr/bin/certutil 
+    certutil -S -d ${CERT_DIR} -n ${TEST_HOSTNAME} -s "CN=${TEST_HOSTNAME}" -t "CT,," -x -f ${CERT_PW_FILE} -z /usr/bin/certutil 
+}
+
+delete_certs() {
+    if [[ -e ${CERT_DIR} ]] ;  then
+        rm -rf ${CERT_DIR}
+    fi
 }
 
 start_broker() {
-    PORT=`../qpidd --daemon --transport ssl --port 0 --ssl-port 0 --no-data-dir --no-module-dir --auth no --config $CONFIG --load-module ../.libs/ssl.so --ssl-cert-db $CERT_DIR --ssl-cert-password-file $CERT_PW_FILE`
+    PORT=`../qpidd --daemon --transport ssl --port 0 --ssl-port 0 --no-data-dir --no-module-dir --auth no --config $CONFIG --load-module ../.libs/ssl.so --ssl-cert-db $CERT_DIR --ssl-cert-password-file $CERT_PW_FILE --ssl-cert-name $TEST_HOSTNAME`
 }
 
 stop_broker() {
@@ -47,6 +53,12 @@ stop_broker() {
         ../qpidd -q --port $PORT
     fi
 }
+
+cleanup() {
+    stop_broker
+    delete_certs
+}
+
 CERTUTIL=$(type -p certutil)
 if [[ !(-x $CERTUTIL) ]] ; then
     echo "No certutil, skipping ssl test";
@@ -56,9 +68,8 @@ fi
 if [[ !(-e ${CERT_PW_FILE}) ]] ;  then
     echo password > ${CERT_PW_FILE}
 fi
-if [[ !(-e ${CERT_DIR}) ]] ;  then
-    create_certs || error "Could not create test certificate"
-fi
+delete_certs
+create_certs || error "Could not create test certificate"
 
 start_broker || error "Could not start broker"
 echo "Running SSL test on port $PORT"
@@ -66,5 +77,5 @@ export QPID_NO_MODULE_DIR=1
 export QPID_LOAD_MODULE=../.libs/sslconnector.so
 export QPID_SSL_CERT_DB=${CERT_DIR}
 export QPID_SSL_CERT_PASSWORD_FILE=${CERT_PW_FILE}
-./perftest --count ${COUNT} --port ${PORT} -P ssl -b $HOSTNAME --summary
+./perftest --count ${COUNT} --port ${PORT} -P ssl -b $TEST_HOSTNAME --summary
 
