Support for multiple protocols in qpid::Url.
- simplified qpid::Address to hold (protocol,host,port) triples.
- protocol plugins call Url:addProtocol to add tags to Url parser.
- use Address::protocol when establishing connections.
- ssl_test: tests using URL to connect.


git-svn-id: https://svn.apache.org/repos/asf/qpid/trunk/qpid@943130 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/cpp/src/tests/ssl_test b/cpp/src/tests/ssl_test
--- a/cpp/src/tests/ssl_test
+++ b/cpp/src/tests/ssl_test
@@ -78,5 +78,11 @@ export QPID_NO_MODULE_DIR=1
 export QPID_LOAD_MODULE=$SSLCONNECTOR_LIB
 export QPID_SSL_CERT_DB=${CERT_DIR}
 export QPID_SSL_CERT_PASSWORD_FILE=${CERT_PW_FILE}
+# Test connection via connection settings
 ./perftest --count ${COUNT} --port ${PORT} -P ssl -b $TEST_HOSTNAME --summary
 
+# Test connection with a URL
+URL=amqp:ssl:$TEST_HOSTNAME:$PORT 
+./qpid_send -b $URL --content-string=hello -a "foo;{create:always}"
+MSG=`./qpid_receive -b $URL -a "foo;{create:always}" --messages 1`
+test "$MSG" = "hello" || { echo "receive failed '$MSG' != 'hello'"; exit 1; }
