Automated C++ client_test and topictest. Andrew Stitcher: patch to change hardcoded 8-0 version numbers to 0-9.
git-svn-id: https://svn.apache.org/repos/asf/incubator/qpid/branches/qpid.0-9@494483 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/cpp/tests/topictest b/cpp/tests/topictest
--- a/cpp/tests/topictest
+++ b/cpp/tests/topictest
@@ -1,7 +1,10 @@
 #!/bin/bash
 # Run the C++ topic test
 
-# Defaults
+# Clean up old log files
+rm -f subscriber_*.log 
+
+# Defaults values 
 SUBSCRIBERS=10
 MESSAGES=2000
 BATCHES=10
@@ -19,13 +22,8 @@ while getopts "s:m:b:" opt ; do
 done
 
 subscribe() {
-    ID=$1
-    echo "subscriber $ID"
-    ./topic_listener > subscriber.$ID 2>&1 || {
-	echo "SUBSCRIBER %ID FAILED: " ;
-	cat subscriber.$ID
-    }
-    rm subscriber.$ID
+    LOG="subscriber_$1.log"
+    ./topic_listener > $LOG 2>&1 && rm -f $LOG 
 }
 
 publish() {
@@ -35,7 +33,5 @@ publish() {
 for ((i=$SUBSCRIBERS ; i--; )); do
     subscribe $i &
 done
-sleep 1
-STATS=~/bin/topictest.times
-echo "---- topictest `date`" >> $STATS
-publish | tee -a $STATS
+
+publish 2>&1 || exit 1
