disable use of module-dir when running examples
git-svn-id: https://svn.eu.apache.org/repos/asf/incubator/qpid/trunk/qpid@662390 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/cpp/examples/verify_all b/cpp/examples/verify_all
--- a/cpp/examples/verify_all
+++ b/cpp/examples/verify_all
@@ -9,7 +9,7 @@ exclude_regexp=$3
 python=${QPID_PYTHON_DIR:-$topsrcdir/python}
 
 trap "$qpidd -q" exit
-export QPID_PORT=`$qpidd -dp0 --data-dir "" --auth no` || { echo "Can't run qpidd" ; exit 1; }
+export QPID_PORT=`$qpidd -dp0 --no-module-dir --data-dir "" --auth no` || { echo "Can't run qpidd" ; exit 1; }
 export PYTHON_EXAMPLES=$python/examples
 export PYTHONPATH=$python:$PYTHONPATH
 
