From:  Jonathan Robie <jrobie@redhat.com>  - Updated examples and verify script.
From me: Integration of verify in make check.


git-svn-id: https://svn.eu.apache.org/repos/asf/incubator/qpid/trunk/qpid@604235 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/cpp/examples/verify b/cpp/examples/verify
--- a/cpp/examples/verify
+++ b/cpp/examples/verify
@@ -5,6 +5,14 @@
 DIR=$PWD
 SRC=`dirname $0 | sed 's|^\([^/].*\)|'$PWD'/\1|'`/examples
 
+# Start private broker if QPIDD is set.
+
+if [ -n "$QPIDD" ] ; then
+    QPID_PORT=`$QPIDD -dp0` || { echo "Cannot start $QPIDD" ; exit 1; }
+    export QPID_PORT
+    trap "$QPIDD -q" EXIT
+fi
+
 # Utility functions
 
 run() {
@@ -28,17 +36,20 @@ remove_uuid() {
 # Scripts for each example
 
 direct() {
-    run ./direct_config_queues  > verify.out
-    run ./direct_publisher >> verify.out
+    run ./declare_queues  > verify.out
+    run ./direct_producer >> verify.out
     run ./listener >> verify.out
-    run ./direct_persistent_config_queues >> verify.out
-    run ./direct_persistent_publisher >> verify.out
+}
+
+persistent() {
+    run ./declare_queues >> verify.out
+    run ./direct_persistent_producer >> verify.out
     run ./listener >> verify.out
 }
 
 fanout() {
-    run ./fanout_config_queues > verify.out
-    run ./fanout_publisher >>verify.out
+    run ./declare_queues > verify.out
+    run ./fanout_producer >>verify.out
     run ./listener >>verify.out
 }
 
@@ -59,11 +70,14 @@ request_response() {
     run remove_uuid server.out >> verify.out
 }
 
+# FIXME aconway 2007-12-14: put back pub-sub and persistence when fixed.
+
 # Main
-for ex in direct fanout pub-sub request-response; do
+for ex in  direct fanout request-response ; do
     func=`echo $ex | tr - _`
     echo "Verifing $ex"
     ( cd $ex && $func && verify && rm -f *.out *.wait) 
 done
 
 exit $RET
+
