Fix example check in rpmbuild.
git-svn-id: https://svn.eu.apache.org/repos/asf/incubator/qpid/trunk@656427 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/qpid/cpp/examples/verify_all b/qpid/cpp/examples/verify_all
--- a/qpid/cpp/examples/verify_all
+++ b/qpid/cpp/examples/verify_all
@@ -3,18 +3,17 @@
 #
 
 verify=`dirname $0`/verify
-topdir=$1 
-exclude_regexp=$2
+topsrcdir=$1
+qpidd=$2
+exclude_regexp=$3
 
-
-qpidd=$topdir/cpp/src/qpidd
-python=$topdir/python
+python=$topsrcdir/python
 
 trap "$qpidd -q" exit
-export QPID_PORT=`$qpidd -dp0 --data-dir "" --auth no`
+export QPID_PORT=`$qpidd -dp0 --data-dir "" --auth no` || { echo "Can't run qpidd" ; exit 1; }
 export PYTHON_EXAMPLES=$python/examples
 export PYTHONPATH=$python:$PYTHONPATH
-export AMQP_SPEC=$topdir/specs/amqp.0-10.xml
+export AMQP_SPEC=$topsrcdir/specs/amqp.0-10.xml
 
 test -d $PYTHON_EXAMPLES || echo "Warning: not verifying python examples, $PYTHON_EXAMPLES not found"
 find="find examples"
