Patch from Manuel Teira: https://issues.apache.org/jira/secure/CommentAssignIssue!default.jspa?action=5&id=12398038  - Use standard automake makefiles to build cpp/examples.  - Rationalize examples directory structure.
Additions to patch:
 - Fix for VPATH builds.
 - Fix make distcheck (finally!)


git-svn-id: https://svn.apache.org/repos/asf/incubator/qpid/trunk@670066 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/qpid/cpp/examples/verify_all b/qpid/cpp/examples/verify_all
--- a/qpid/cpp/examples/verify_all
+++ b/qpid/cpp/examples/verify_all
@@ -9,9 +9,10 @@ exclude_regexp=$3
 python=${QPID_PYTHON_DIR:-$topsrcdir/python}
 
 trap "$qpidd -q" exit
-export QPID_PORT=`$qpidd -dp0 --no-module-dir --data-dir "" --auth no` || { echo "Can't run qpidd" ; exit 1; }
-export PYTHON_EXAMPLES=$python/examples
-export PYTHONPATH=$python:$PYTHONPATH
+QPID_PORT=`$qpidd -dp0 --no-module-dir --data-dir "" --auth no` || { echo "Can't run qpidd" ; exit 1; }
+PYTHON_EXAMPLES=$python/examples
+PYTHONPATH=$python:$PYTHONPATH
+export QPID_PORT PYTHON_EXAMPLES PYTHONPATH
 
 test -d $PYTHON_EXAMPLES || echo "WARNING: No python examples. $PYTHON_EXAMPLES not found."
 find="find examples"
