verify: starts its own broker when run in build. Makefile.am: fixed verify issues.
git-svn-id: https://svn.eu.apache.org/repos/asf/incubator/qpid/trunk@604249 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/qpid/cpp/examples/verify b/qpid/cpp/examples/verify
--- a/qpid/cpp/examples/verify
+++ b/qpid/cpp/examples/verify
@@ -8,8 +8,10 @@ SRC=`dirname $0 | sed 's|^\([^/].*\)|'$PWD'/\1|'`/examples
 # Start private broker if QPIDD is set.
 
 if [ -n "$QPIDD" ] ; then
-    QPID_PORT=`$QPIDD -dp0` || { echo "Cannot start $QPIDD" ; exit 1; }
-    export QPID_PORT
+    # FIXME aconway 2007-12-14: Should use --port 0, need
+    # to make examples clients more flexible to connect.
+    # 
+    $QPIDD -d || { echo "Cannot start $QPIDD" ; exit 1; }
     trap "$QPIDD -q" EXIT
 fi
 
@@ -73,7 +75,7 @@ request_response() {
 # FIXME aconway 2007-12-14: put back pub-sub and persistence when fixed.
 
 # Main
-for ex in  direct fanout request-response ; do
+for ex in  direct fanout request-response  ; do
     func=`echo $ex | tr - _`
     echo "Verifing $ex"
     ( cd $ex && $func && verify && rm -f *.out *.wait) 
