QPID-7207: Create independent cpp and python subtrees, with content from tools and extras
git-svn-id: https://svn.apache.org/repos/asf/qpid/trunk@1740289 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/qpid/cpp/src/tests/dynamic_log_hires_timestamp b/qpid/cpp/src/tests/dynamic_log_hires_timestamp
--- a/qpid/cpp/src/tests/dynamic_log_hires_timestamp
+++ b/qpid/cpp/src/tests/dynamic_log_hires_timestamp
@@ -20,14 +20,14 @@
 #
 
 # Run a simple test to verify dynamic log highres timestamp changes
-source ./test_env.sh
-test -d $PYTHON_DIR || { echo "Skipping python tests, no python dir."; exit 0; }
+
+source ./env.sh
 
 LOG_FILE=hires_test.log
 trap cleanup EXIT
 
 cleanup() {
-    test -n "$PORT" && $QPIDD_EXEC --no-module-dir --quit --port $PORT
+    test -n "$PORT" && qpidd --no-module-dir --quit --port $PORT
 }
 
 error() { 
@@ -36,16 +36,16 @@ error() {
 }
 
 rm -rf $LOG_FILE
-PORT=$($QPIDD_EXEC --auth=no --no-module-dir --daemon --port=0  --interface 127.0.0.1 --log-to-file $LOG_FILE) || error "Could not start broker"
+PORT=$(qpidd --auth=no --no-module-dir --daemon --port=0  --interface 127.0.0.1 --log-to-file $LOG_FILE) || error "Could not start broker"
 
-echo Broker for log highres timestamp test started on $PORT, pid is $($QPIDD_EXEC --no-module-dir --check --port $PORT)
+echo Broker for log highres timestamp test started on $PORT, pid is $(qpidd --no-module-dir --check --port $PORT)
 
-$srcdir/qpid-ctrl -b localhost:$PORT setLogLevel level='debug+:Broker' > /dev/null
-$srcdir/qpid-ctrl -b localhost:$PORT echo sequence=1 body=LOWRES > /dev/null
-$srcdir/qpid-ctrl -b localhost:$PORT setLogHiresTimestamp logHires='true' > /dev/null
-$srcdir/qpid-ctrl -b localhost:$PORT echo sequence=2 body=HI_RES > /dev/null
-$srcdir/qpid-ctrl -b localhost:$PORT setLogHiresTimestamp logHires='false' > /dev/null
-$srcdir/qpid-ctrl -b localhost:$PORT echo sequence=3 body=LOWRES > /dev/null
+qpid-ctrl -b localhost:$PORT setLogLevel level='debug+:Broker' > /dev/null
+qpid-ctrl -b localhost:$PORT echo sequence=1 body=LOWRES > /dev/null
+qpid-ctrl -b localhost:$PORT setLogHiresTimestamp logHires='true' > /dev/null
+qpid-ctrl -b localhost:$PORT echo sequence=2 body=HI_RES > /dev/null
+qpid-ctrl -b localhost:$PORT setLogHiresTimestamp logHires='false' > /dev/null
+qpid-ctrl -b localhost:$PORT echo sequence=3 body=LOWRES > /dev/null
 
 # Expect 3 log entries with 'echo' in them
 if [[ $(grep echo $LOG_FILE | wc -l) -ne 3 ]]; then 
diff --git a/qpid/cpp/src/tests/dynamic_log_level_test b/qpid/cpp/src/tests/dynamic_log_level_test
--- a/qpid/cpp/src/tests/dynamic_log_level_test
+++ b/qpid/cpp/src/tests/dynamic_log_level_test
@@ -20,14 +20,14 @@
 #
 
 # Run a simple test to verify dynamic log level changes
-source ./test_env.sh
-test -d $PYTHON_DIR || { echo "Skipping python tests, no python dir."; exit 0; }
+
+source ./env.sh
 
 LOG_FILE=log_test.log
 trap cleanup EXIT
 
 cleanup() {
-    test -n "$PORT" && $QPIDD_EXEC --no-module-dir --quit --port $PORT
+    test -n "$PORT" && qpidd --no-module-dir --quit --port $PORT
 }
 
 error() { 
@@ -43,30 +43,30 @@ checklog() {
 }
 
 rm -rf $LOG_FILE
-PORT=$($QPIDD_EXEC --auth=no --no-module-dir --daemon --port=0  --interface 127.0.0.1 --log-to-file $LOG_FILE) || error "Could not start broker"
+PORT=$(qpidd --auth=no --no-module-dir --daemon --port=0  --interface 127.0.0.1 --log-to-file $LOG_FILE) || error "Could not start broker"
 
-echo Broker for log level test started on $PORT, pid is $($QPIDD_EXEC --no-module-dir --check --port $PORT)
+echo Broker for log level test started on $PORT, pid is $(qpidd --no-module-dir --check --port $PORT)
 
 # Set level to notice+ and send an echo request
 # The 'echo' in the log is hidden since it is at debug level.
-$srcdir/qpid-ctrl -b localhost:$PORT setLogLevel level='notice+' > /dev/null
-$srcdir/qpid-ctrl -b localhost:$PORT echo sequence=1 body=HIDDEN > /dev/null
+qpid-ctrl -b localhost:$PORT setLogLevel level='notice+' > /dev/null
+qpid-ctrl -b localhost:$PORT echo sequence=1 body=HIDDEN > /dev/null
 checklog 0 "Step 1 Expected no echo log entries"
 
 # Next, enable all Broker logs at debug and higher levels and send another echo
 # This 'echo' should be in the log.
-$srcdir/qpid-ctrl -b localhost:$PORT setLogLevel level='debug+:Broker' > /dev/null
-$srcdir/qpid-ctrl -b localhost:$PORT echo sequence=2 body=VISIBLE > /dev/null
+qpid-ctrl -b localhost:$PORT setLogLevel level='debug+:Broker' > /dev/null
+qpid-ctrl -b localhost:$PORT echo sequence=2 body=VISIBLE > /dev/null
 checklog 1 "Step 2 Expected one echo log entry"
 
 # Now turn on Broker debug messages but specifically disable ManagementMethod logs
 # The 'echo' should be hidden.
-$srcdir/qpid-ctrl -b localhost:$PORT setLogLevel level='debug+:Broker !debug+:broker::Broker::ManagementMethod' > /dev/null
-$srcdir/qpid-ctrl -b localhost:$PORT echo sequence=3 body=HIDDEN > /dev/null
+qpid-ctrl -b localhost:$PORT setLogLevel level='debug+:Broker !debug+:broker::Broker::ManagementMethod' > /dev/null
+qpid-ctrl -b localhost:$PORT echo sequence=3 body=HIDDEN > /dev/null
 checklog 1 "Step 3 Expected one echo log entry"
 
 # Verify that the management get returns what was just set
-$srcdir/qpid-ctrl -b localhost:$PORT getLogLevel > dynamic_log_level.tmp
+qpid-ctrl -b localhost:$PORT getLogLevel > dynamic_log_level.tmp
 if [[ $(grep 'level=debug+:Broker,!debug+:broker::Broker::ManagementMethod' dynamic_log_level.tmp | wc -l) -ne 1 ]]; then
     error "Step 4 getLogLevel returned unexpected value: " `cat dynamic_log_level.tmp`
 fi
@@ -76,10 +76,10 @@ cleanup
 
 # Start another broker with --log-disable settings and make sure the management string receives them
 rm -rf $LOG_FILE
-PORT=$($QPIDD_EXEC --auth=no --no-module-dir --daemon --port=0  --interface 127.0.0.1 --log-to-file $LOG_FILE --log-enable debug:foo --log-disable debug:bar) || error "Could not start broker"
-echo Broker for log level test started on $PORT, pid is $($QPIDD_EXEC --no-module-dir --check --port $PORT)
+PORT=$(qpidd --auth=no --no-module-dir --daemon --port=0  --interface 127.0.0.1 --log-to-file $LOG_FILE --log-enable debug:foo --log-disable debug:bar) || error "Could not start broker"
+echo Broker for log level test started on $PORT, pid is $(qpidd --no-module-dir --check --port $PORT)
 
-$srcdir/qpid-ctrl -b localhost:$PORT getLogLevel > dynamic_log_level.tmp
+qpid-ctrl -b localhost:$PORT getLogLevel > dynamic_log_level.tmp
 if [[ $(grep 'level=debug:foo,!debug:bar' dynamic_log_level.tmp | wc -l) -ne 1 ]]; then
     error "Step 5 getLogLevel returned unexpected value: " `cat dynamic_log_level.tmp`
 fi
diff --git a/qpid/cpp/src/tests/sasl_fed_ex b/qpid/cpp/src/tests/sasl_fed_ex
--- a/qpid/cpp/src/tests/sasl_fed_ex
+++ b/qpid/cpp/src/tests/sasl_fed_ex
@@ -25,86 +25,47 @@
 # transport-layer security.
 #===============================================================================
 
-source $QPID_TEST_COMMON
+set -eu
 
-ensure_python_tests
-
-script_name=`basename $0`
-
-if [ $# -lt 1 ] || [ $# -gt 2 ]
-then
-  echo
-  # These are the four different ways of creating links ( or routes+links ) 
-  # that the qpid-route command provides.
-  echo "Usage: ${script_name} dynamic|link|queue|route"
-  echo
-  exit 1
+if (( $# != 1 )); then
+    # These are the four different ways of creating links ( or routes+links ) 
+    # that the qpid-route command provides.
+    echo "Usage: $(basename $0) dynamic|link|queue|route"
+    exit 1
 fi
 
 qpid_route_method=$1
 
-# Debugging print. --------------------------
-debug=
-function print {
-  if [ "$debug" ]; then
-    echo "${script_name}: $1"
-  fi
-}
+WORK_DIR="${WORK_DIR}/sasl_fed_ex_${qpid_route_method}"
+mkdir $WORK_DIR
 
-print "=========== start sasl_fed_ex $* ============"
-
-
-
-# This minimum value corresponds to sasl version 2.1.22
-minimum_sasl_version=131350
-
-sasl_version=`$QPID_TEST_EXEC_DIR/sasl_version`
-
-# This test is necessary because this sasl version is the first one that permits 
-# redirection of the sasl config file path.
-if [ "$sasl_version" -lt  "$minimum_sasl_version" ]; then
-  echo "sasl_fed: must have sasl version 2.1.22 or greater.  ( Integer value: $minimum_sasl_version )  Version is: $sasl_version"
-  exit 0
-fi
-
-CERT_DIR=`pwd`/test_cert_db
-CERT_PW_FILE=`pwd`/cert.password
+CERT_DIR=$WORK_DIR/test_cert_db
+CERT_PW_FILE=$WORK_DIR/cert.password
 TEST_HOSTNAME=127.0.0.1
 
 create_certs() {
-    #create certificate and key databases with single, simple, self-signed certificate in it
+    # Create certificate and key databases with single, simple,
+    # self-signed certificate in it
     mkdir ${CERT_DIR}
     certutil -N -d ${CERT_DIR} -f ${CERT_PW_FILE}
     certutil -S -d ${CERT_DIR} -n ${TEST_HOSTNAME} -s "CN=${TEST_HOSTNAME}" -t "CT,," -x -f ${CERT_PW_FILE} -z /bin/sh 2> /dev/null
 }
 
-delete_certs() {
-    if [[ -e ${CERT_DIR} ]] ;  then
-        print "removing cert dir ${CERT_DIR}"
-        rm -rf ${CERT_DIR}
-    fi
-}
-
-
 CERTUTIL=$(type -p certutil)
-if [[ !(-x $CERTUTIL) ]] ; then
-    echo "No certutil, skipping ssl test";
-    exit 0;
+
+if [[ ! -x $CERTUTIL ]]; then
+    echo "No certutil, skipping ssl test"
+    exit 0
 fi
 
-delete_certs
 create_certs 2> /dev/null
-if [ ! $? ]; then
-  error "Could not create test certificate"
-  exit 1
+
+if (( $? != 0 )); then
+    echo "Could not create test certificate"
+    exit 1
 fi
 
-sasl_config_dir=$QPID_TEST_EXEC_DIR/sasl_config
-
-tmp_root=$QPID_TEST_EXEC_DIR/sasl_fed_ex_temp
-print "results dir is ${tmp_root}"
-rm -rf ${tmp_root}
-mkdir -p $tmp_root
+sasl_config_dir=$BUILD_DIR/src/tests/sasl_config
 
 SRC_SSL_PORT=6667
 DST_SSL_PORT=6666
@@ -125,8 +86,6 @@ export QPID_SSL_CERT_DB=${CERT_DIR}
 export QPID_SSL_CERT_PASSWORD_FILE=${CERT_PW_FILE}
 export QPID_SSL_CERT_NAME=${TEST_HOSTNAME}
 
-
-
 #######################################
 # Understanding this Plumbing
 #######################################
@@ -146,7 +105,7 @@ export QPID_SSL_CERT_NAME=${TEST_HOSTNAME}
 
 COMMON_BROKER_OPTIONS="                          \
       --ssl-sasl-no-dict                         \
-      --sasl-config=$sasl_config_dir             \
+      --sasl-config $sasl_config_dir             \
       --ssl-require-client-authentication        \
       --auth yes                                 \
       --ssl-cert-db $CERT_DIR                    \
@@ -154,130 +113,111 @@ COMMON_BROKER_OPTIONS="                          \
       --ssl-cert-name $TEST_HOSTNAME             \
       --no-data-dir                              \
       --no-module-dir                            \
-      --mgmt-enable=yes                          \
+      --mgmt-enable yes                          \
       --log-enable info+                         \
       --log-source yes                           \
-      --daemon "                                 
+      --daemon"                                 
                       
-
 function start_brokers {
     # vanilla brokers --------------------------------
-    print "Starting SRC broker"
-    $QPIDD_EXEC                                  \
+    echo "Starting SRC broker"
+    qpidd                                          \
 	--port=${SRC_TCP_PORT}                     \
 	--ssl-port ${SRC_SSL_PORT}                 \
 	${COMMON_BROKER_OPTIONS}                   \
-	--log-to-file $tmp_root/qpidd_src.log 2> /dev/null
+	--log-to-file $WORK_DIR/qpidd_src.log 2> /dev/null
 
     broker_ports[0]=${SRC_TCP_PORT}
 
-    print "Starting DST broker"
-    $QPIDD_EXEC                                  \
+    echo "Starting DST broker"
+    qpidd                                          \
 	--port=${DST_TCP_PORT}                     \
 	--ssl-port ${DST_SSL_PORT}                 \
 	${COMMON_BROKER_OPTIONS}                   \
-	--log-to-file $tmp_root/qpidd_dst.log 2> /dev/null
+	--log-to-file $WORK_DIR/qpidd_dst.log 2> /dev/null
 
     broker_ports[1]=${DST_TCP_PORT}
 }
 
 function halt_brokers {
-  n_brokers=${#broker_ports[@]}
-  print "Halting ${n_brokers} brokers."
-  for i in $(seq 0 $((${n_brokers} - 1)))
-  do
-    halt_port=${broker_ports[$i]}
-    print "Halting broker $i on port ${halt_port}"
-    $QPIDD_EXEC --port ${halt_port} --quit
-  done
-
+    n_brokers=${#broker_ports[@]}
+    echo "Halting ${n_brokers} brokers"
+    for i in $(seq 0 $((${n_brokers} - 1))); do
+        halt_port=${broker_ports[$i]}
+        echo "Halting broker $i on port ${halt_port}"
+        qpidd --port ${halt_port} --quit
+    done
 }
 
-
 start_brokers
-
+trap halt_brokers EXIT
 
 # I am not randomizing these names, because this test creates its own brokers.
 QUEUE_NAME=sasl_fed_queue
 ROUTING_KEY=sasl_fed_queue
 EXCHANGE_NAME=sasl_fedex
 
+echo "Add exchanges"
+qpid-config -b localhost:${SRC_TCP_PORT} add exchange direct $EXCHANGE_NAME
+qpid-config -b localhost:${DST_TCP_PORT} add exchange direct $EXCHANGE_NAME
 
-print "add exchanges"
-$QPID_CONFIG_EXEC -b localhost:${SRC_TCP_PORT} add exchange direct $EXCHANGE_NAME
-$QPID_CONFIG_EXEC -b localhost:${DST_TCP_PORT} add exchange direct $EXCHANGE_NAME
+echo "Add queues"
+qpid-config -b localhost:${SRC_TCP_PORT} add queue $QUEUE_NAME
+qpid-config -b localhost:${DST_TCP_PORT} add queue $QUEUE_NAME
 
-
-print "add queues"
-$QPID_CONFIG_EXEC -b localhost:${SRC_TCP_PORT} add queue $QUEUE_NAME
-$QPID_CONFIG_EXEC -b localhost:${DST_TCP_PORT} add queue $QUEUE_NAME
-
-
-print "create bindings"
-$QPID_CONFIG_EXEC -b localhost:${SRC_TCP_PORT} bind $EXCHANGE_NAME $QUEUE_NAME $ROUTING_KEY
-$QPID_CONFIG_EXEC -b localhost:${DST_TCP_PORT} bind $EXCHANGE_NAME $QUEUE_NAME $ROUTING_KEY
-
+echo "Create bindings"
+qpid-config -b localhost:${SRC_TCP_PORT} bind $EXCHANGE_NAME $QUEUE_NAME $ROUTING_KEY
+qpid-config -b localhost:${DST_TCP_PORT} bind $EXCHANGE_NAME $QUEUE_NAME $ROUTING_KEY
 
 #
 # NOTE: The SRC broker *must* be referred to as $TEST_HOSTNAME, and not as "localhost".
 #       It must be referred to by the exact string given as the Common Name (CN) in the cert,
 #       which was created in the function create_certs, above.
 
-
-
 #----------------------------------------------------------------
 # Use qpid-route to create the link, or the link+route, depending
 # on which of its several methods was requested.
 #----------------------------------------------------------------
-if   [ ${qpid_route_method} == "dynamic" ]; then
-  print "dynamic add"
-  $QPID_ROUTE_EXEC -t ssl dynamic add localhost:${DST_TCP_PORT} $TEST_HOSTNAME:${SRC_SSL_PORT} $EXCHANGE_NAME "" "" EXTERNAL
-elif [ ${qpid_route_method} == "link"   ];  then
-  print "link add"
-  $QPID_ROUTE_EXEC -t ssl link add localhost:${DST_TCP_PORT} $TEST_HOSTNAME:${SRC_SSL_PORT}  EXTERNAL
-elif [ ${qpid_route_method} == "queue" ];   then
-  print "queue add"
-  $QPID_ROUTE_EXEC -t ssl queue add localhost:${DST_TCP_PORT}   $TEST_HOSTNAME:${SRC_SSL_PORT} $EXCHANGE_NAME $ROUTING_KEY EXTERNAL
-elif [ ${qpid_route_method} == "route" ];   then
-  print "route add"
-  $QPID_ROUTE_EXEC -t ssl route add localhost:${DST_TCP_PORT}   $TEST_HOSTNAME:${SRC_SSL_PORT} $EXCHANGE_NAME $ROUTING_KEY "" "" EXTERNAL
+if   [[ $qpid_route_method == "dynamic" ]]; then
+    echo "Dynamic add"
+    qpid-route -t ssl dynamic add localhost:${DST_TCP_PORT} $TEST_HOSTNAME:${SRC_SSL_PORT} $EXCHANGE_NAME "" "" EXTERNAL || :
+elif [[ $qpid_route_method == "link"    ]];  then
+    echo "Link add"
+    qpid-route -t ssl link add localhost:${DST_TCP_PORT}    $TEST_HOSTNAME:${SRC_SSL_PORT} EXTERNAL || :
+elif [[ $qpid_route_method == "queue"   ]];   then
+    echo "Queue add"
+    qpid-route -t ssl queue add localhost:${DST_TCP_PORT}   $TEST_HOSTNAME:${SRC_SSL_PORT} $EXCHANGE_NAME $ROUTING_KEY EXTERNAL || :
+elif [[ $qpid_route_method == "route"   ]];   then
+    echo "Route add"
+    qpid-route -t ssl route add localhost:${DST_TCP_PORT}   $TEST_HOSTNAME:${SRC_SSL_PORT} $EXCHANGE_NAME $ROUTING_KEY "" "" EXTERNAL || :
 else
-  echo "unknown method: |${qpid_route_method}|"
-  echo " choices are: dynamic|link|queue|route "
-  halt_brokers
-  exit 1
+    echo "Unknown method: |${qpid_route_method}|"
+    echo "Choices are: dynamic|link|queue|route "
+    halt_brokers
+    exit 1
 fi
-
 
 # I don't know how to avoid this sleep yet.  It has to come after route-creation 
 # to avoid false negatives.
 sleep 5
 
 # Look only at the transport field, which should be "ssl".
-print "check the link"
-link_status=$($QPID_ROUTE_EXEC link list localhost:${DST_TCP_PORT} | tail -1 | awk '{print $3}')
-
-halt_brokers
+echo "Check the link"
+link_status=$(qpid-route link list localhost:${DST_TCP_PORT} | tail -1 | awk '{print $3}')
 
 sleep 1
 
-if [ ! ${link_status} ]; then
-  print "link_status is empty"
-  print "result: fail"
-  exit 2
+if [[ ! $link_status ]]; then
+    echo "Link status is empty"
+    echo "Result: fail"
+    exit 2
 fi
 
-if [ ${link_status} == "ssl" ]; then
-  print "result: good"
-  # Only remove the tmp_root on success, to permit debugging.
-  print "Removing temporary directory $tmp_root"
-  rm -rf $tmp_root
-  exit 0
+if [[ $link_status == "ssl" ]]; then
+    echo "Result: good"
+    exit 0
 fi
 
-print "link_status has a bad value: ${link_status}"
-print "result: fail"
+echo "Link status has a bad value: ${link_status}"
+echo "Result: fail"
 exit 3
-
-
-
diff --git a/qpid/cpp/src/tests/sasl_no_dir b/qpid/cpp/src/tests/sasl_no_dir
--- a/qpid/cpp/src/tests/sasl_no_dir
+++ b/qpid/cpp/src/tests/sasl_no_dir
@@ -19,88 +19,40 @@
 # under the License.
 #
 
-script_name=`basename $0`
+set -eu
 
-# This minimum value corresponds to sasl version 2.1.22
-minimum_sasl_version=131350
+sasl_config_dir=$BUILD_DIR/not_there_at_all
 
-sasl_version=$($QPID_TEST_EXEC_DIR/sasl_version)
+WORK_DIR=$WORK_DIR/sasl_no_dir
+mkdir $WORK_DIR
 
-# This test is necessary because this sasl version is the first one that permits 
-# redirection of the sasl config file path.
-if [ "$sasl_version" -lt  "$minimum_sasl_version" ]; then
-  echo "sasl_fed: must have sasl version 2.1.22 or greater.  ( Integer value: $minimum_sasl_version )  Version is: $sasl_version"
-  exit 0
-fi
+LOG_FILE=$WORK_DIR/qpidd.log
 
-
-sasl_config_dir=$QPID_TEST_EXEC_DIR/sasl_config
-
-
-# Debugging print. --------------------------
-debug=
-function print {
-  if [ "$debug" ]; then
-    echo "${script_name}: $1"
-  fi
-}
-
-
-my_random_number=$RANDOM
-tmp_root=/tmp/sasl_fed_$my_random_number
-mkdir -p $tmp_root
-
-
-LOG_FILE=$tmp_root/qpidd.log
-
-# If you want to see this test fail, just comment out this 'mv' command.
-print "Moving sasl configuration dir."
-mv ${sasl_config_dir} ${sasl_config_dir}-
-
-
-#--------------------------------------------------
-print " Starting broker"
-#--------------------------------------------------
-$QPIDD_EXEC                                  \
-  -p 0  --interface 127.0.0.1                \
-  --no-data-dir                              \
-  --auth=yes                                 \
-  --mgmt-enable=yes                          \
-  --log-enable info+                         \
-  --log-source yes                           \
-  --log-to-file ${LOG_FILE}                  \
-  --sasl-config=$sasl_config_dir             \
-  -d 2> /dev/null  1> $tmp_root/broker_port
-
-
+echo "Starting broker"
+qpidd                                          \
+    -p 0  --interface 127.0.0.1                \
+    --no-data-dir                              \
+    --auth=yes                                 \
+    --mgmt-enable=yes                          \
+    --log-enable info+                         \
+    --log-source yes                           \
+    --log-to-file ${LOG_FILE}                  \
+    --sasl-config=$sasl_config_dir             \
+    -d 2> /dev/null 1> $WORK_DIR/broker_port || :
 
 # If it works right, the output will look something like this:  ( two lines long )
 # Daemon startup failed: SASL: sasl_set_path failed: no such directory: /home/mick/trunk/qpid/cpp/src/tests/sasl_config (qpid/broker/SaslAuthenticator.cpp:112)
 # 2011-10-13 14:07:00 critical qpidd.cpp:83: Unexpected error: Daemon startup failed: SASL: sasl_set_path failed: no such directory: /home/mick/trunk/qpid/cpp/src/tests/sasl_config (qpid/broker/SaslAuthenticator.cpp:112)
 
-result=`cat ${LOG_FILE} | grep "sasl_set_path failed: no such directory" | wc -l `
+result=$(cat ${LOG_FILE} | grep "sasl_set_path failed: no such directory" | wc -l)
 
-#--------------------------------------------------
-print "Restore the Sasl config dir to its original place."
-#--------------------------------------------------
-mv ${sasl_config_dir}- ${sasl_config_dir}
-
-if [ "2" -eq ${result} ]; then
-  print "result: success"
-  rm -rf $tmp_root
-  exit 0
+if (( $result == 2 )); then
+    echo "Result: success"
+    exit 0
 fi
 
+broker_port=$(cat $WORK_DIR/broker_port)
+qpidd --port ${broker_port} --quit
 
-# If this test fails, the broker is still alive.
-# Kill it.
-broker_port=`cat $tmp_root/broker_port`
-#--------------------------------------------------
-print "Asking broker to quit."
-#--------------------------------------------------
-$QPIDD_EXEC --port $broker_port --quit
-
-rm -rf $tmp_root
-
-print "result: fail"
+echo "Result: fail"
 exit 1
diff --git a/qpid/cpp/src/tests/ssl_test b/qpid/cpp/src/tests/ssl_test
--- a/qpid/cpp/src/tests/ssl_test
+++ b/qpid/cpp/src/tests/ssl_test
@@ -21,9 +21,11 @@
 
 # Run a simple test over SSL
 
+source env.sh
+
 #set -x
 
-CONFIG=$(dirname $0)/config.null
+CONFIG=$(dirname $0)/qpidd-empty.conf
 TEST_CERT_DIR=`pwd`/test_cert_dir
 CERT_DB=${TEST_CERT_DIR}/test_cert_db
 CERT_PW_FILE=`pwd`/cert.password
@@ -32,7 +34,7 @@ TEST_CLIENT_CERT=rumplestiltskin
 CA_PEM_FILE=${TEST_CERT_DIR}/ca_cert.pem
 OTHER_CA_CERT_DB=${TEST_CERT_DIR}/x_ca_cert_db
 OTHER_CA_PEM_FILE=${TEST_CERT_DIR}/other_ca_cert.pem
-PY_PING_BROKER=${QPID_TEST_SRC_DIR}/ping_broker
+PY_PING_BROKER=$SOURCE_DIR/src/tests/ping_broker
 COUNT=10
 
 if [[ -a $AMQP_LIB ]] ; then
@@ -93,7 +95,7 @@ delete_certs() {
     fi
 }
 
-# Don't need --no-module-dir or --no-data-dir as they are set as env vars in test_env.sh
+# Don't need --no-module-dir or --no-data-dir as they are set as env vars in env.sh
 COMMON_OPTS="--daemon --config $CONFIG --ssl-cert-db $CERT_DB --ssl-cert-password-file $CERT_PW_FILE --ssl-cert-name $TEST_HOSTNAME"
 
 # Start new brokers:
@@ -103,7 +105,7 @@ COMMON_OPTS="--daemon --config $CONFIG --ssl-cert-db $CERT_DB --ssl-cert-passwor
 start_brokers() {
     local -a ports
     for (( i=0; $i<$1; i++)) do
-    ports[$i]=$($QPIDD_EXEC --port 0 --interface 127.0.0.1 $COMMON_OPTS $2) || error "Could not start broker $i"
+    ports[$i]=$(qpidd --port 0 --interface 127.0.0.1 $COMMON_OPTS $2) || error "Could not start broker $i"
     done
     PORTS=( ${PORTS[@]} ${ports[@]} )
 }
@@ -111,7 +113,7 @@ start_brokers() {
 # Stop single broker:
 #   $1 is number of broker to stop (0 based)
 stop_broker() {
-    $QPIDD_EXEC -qp ${PORTS[$1]}
+    qpidd -qp ${PORTS[$1]}
 
     # Remove from ports array
     unset PORTS[$1]
@@ -120,15 +122,15 @@ stop_broker() {
 stop_brokers() {
     for port in "${PORTS[@]}";
     do
-        $QPIDD_EXEC -qp $port
+        qpidd -qp $port
     done
     PORTS=()
 }
 
 pick_port() {
     # We need a fixed port to set --cluster-url. Use qpidd to pick a free port.
-    PICK=`../qpidd --no-module-dir --listen-disable ssl -dp0`
-    ../qpidd --no-module-dir -qp $PICK
+    PICK=`qpidd --no-module-dir --listen-disable ssl -dp0`
+    qpidd --no-module-dir -qp $PICK
     echo $PICK
 }
 
@@ -143,11 +145,11 @@ start_ssl_broker() {
 }
 
 start_ssl_mux_broker() {
-    ../qpidd $COMMON_OPTS --port $1 --ssl-port $1 --auth no
+    qpidd $COMMON_OPTS --port $1 --ssl-port $1 --auth no
     PORTS=( ${PORTS[@]} $1 )
 }
 
-sasl_config_dir=$QPID_TEST_EXEC_DIR/sasl_config
+sasl_config_dir=$BUILD_DIR/src/tests/sasl_config
 
 start_authenticating_broker() {
     start_brokers 1 "--transport ssl --ssl-port 0 --require-encryption --ssl-sasl-no-dict --ssl-require-client-authentication --auth yes --sasl-config=${sasl_config_dir} $MODULES"
@@ -180,25 +182,25 @@ export QPID_SSL_CERT_DB=${CERT_DB}
 export QPID_SSL_CERT_PASSWORD_FILE=${CERT_PW_FILE}
 
 ## Test connection via connection settings
-./qpid-perftest --count ${COUNT} --port ${PORT} -P ssl -b $TEST_HOSTNAME --summary
+qpid-perftest --count ${COUNT} --port ${PORT} -P ssl -b $TEST_HOSTNAME --summary
 
 ## Test connection with a URL
 URL=amqp:ssl:$TEST_HOSTNAME:$PORT
-./qpid-send -b $URL --content-string=hello -a "foo;{create:always}"
-MSG=`./qpid-receive -b $URL -a "foo;{create:always}" --messages 1`
+qpid-send -b $URL --content-string=hello -a "foo;{create:always}"
+MSG=`qpid-receive -b $URL -a "foo;{create:always}" --messages 1`
 test "$MSG" = "hello" || { echo "receive failed '$MSG' != 'hello'"; exit 1; }
 
 if [[ -a $AMQP_LIB ]] ; then
     echo "Testing ssl over AMQP 1.0"
-    ./qpid-send --connection-options '{protocol:amqp1.0}'  -b $URL --content-string=hello -a "foo;{create:always}"
-    MSG=`./qpid-receive --connection-options '{protocol:amqp1.0}' -b $URL -a "foo;{create:always}" --messages 1`
+    qpid-send --connection-options '{protocol:amqp1.0}'  -b $URL --content-string=hello -a "foo;{create:always}"
+    MSG=`qpid-receive --connection-options '{protocol:amqp1.0}' -b $URL -a "foo;{create:always}" --messages 1`
     test "$MSG" = "hello" || { echo "receive failed for AMQP 1.0 '$MSG' != 'hello'"; exit 1; }
 fi
 
 ## Test connection with a combination of URL and connection options (in messaging API)
 URL=$TEST_HOSTNAME:$PORT
-./qpid-send -b $URL --connection-options '{transport:ssl,heartbeat:2}' --content-string='hello again' -a "foo;{create:always}"
-MSG=`./qpid-receive -b $URL --connection-options '{transport:ssl,heartbeat:2}' -a "foo;{create:always}" --messages 1`
+qpid-send -b $URL --connection-options '{transport:ssl,heartbeat:2}' --content-string='hello again' -a "foo;{create:always}"
+MSG=`qpid-receive -b $URL --connection-options '{transport:ssl,heartbeat:2}' -a "foo;{create:always}" --messages 1`
 test "$MSG" = "hello again" || { echo "receive failed '$MSG' != 'hello again'"; exit 1; }
 
 ## Test using the Python client
@@ -218,14 +220,14 @@ echo "Running SSL client authentication test on port $PORT2"
 URL=amqp:ssl:$TEST_HOSTNAME:$PORT2
 
 ## See if you can set the SSL cert-name for the connection
-./qpid-send -b $URL --connection-options "{ssl-cert-name: $TEST_CLIENT_CERT }"  --content-string=hello -a "bar;{create:always}"
-MSG2=`./qpid-receive -b $URL  --connection-options "{ssl-cert-name: $TEST_CLIENT_CERT }" -a "bar;{create:always}" --messages 1`
+qpid-send -b $URL --connection-options "{ssl-cert-name: $TEST_CLIENT_CERT }"  --content-string=hello -a "bar;{create:always}"
+MSG2=`qpid-receive -b $URL  --connection-options "{ssl-cert-name: $TEST_CLIENT_CERT }" -a "bar;{create:always}" --messages 1`
 test "$MSG2" = "hello" || { echo "receive failed '$MSG2' != 'hello'"; exit 1; }
 
 
 ## Make sure that connect fails with an invalid SSL cert-name
-./qpid-send -b $URL --connection-options "{ssl-cert-name: pignose }" --content-string=hello -a "baz;{create:always}" 2>/dev/null 1>/dev/null
-MSG3=`./qpid-receive -b $URL  --connection-options "{ssl-cert-name: pignose }" -a "baz;{create:always}" --messages 1 2>/dev/null`
+qpid-send -b $URL --connection-options "{ssl-cert-name: pignose }" --content-string=hello -a "baz;{create:always}" 2>/dev/null 1>/dev/null
+MSG3=`qpid-receive -b $URL  --connection-options "{ssl-cert-name: pignose }" -a "baz;{create:always}" --messages 1 2>/dev/null`
 test "$MSG3" = "" || { echo "receive succeeded without valid ssl cert '$MSG3' != ''"; exit 1; }
 
 ## Set the userid in the message to the authenticated username
@@ -243,8 +245,8 @@ start_ssl_mux_broker $PORT || error "Could not start broker"
 echo "Running SSL/TCP mux test on fixed port $PORT"
 
 ## Test connection via connection settings
-./qpid-perftest --count ${COUNT} --port ${PORT} -P ssl -b $TEST_HOSTNAME --summary || error "SSL connection failed!"
-./qpid-perftest --count ${COUNT} --port ${PORT} -P tcp -b $TEST_HOSTNAME --summary || error "TCP connection failed!"
+qpid-perftest --count ${COUNT} --port ${PORT} -P ssl -b $TEST_HOSTNAME --summary || error "SSL connection failed!"
+qpid-perftest --count ${COUNT} --port ${PORT} -P tcp -b $TEST_HOSTNAME --summary || error "TCP connection failed!"
 
 # Test a broker chosen port - since ssl chooses port need to use --transport ssl here
 start_ssl_broker
@@ -252,8 +254,8 @@ PORT=${PORTS[0]}
 echo "Running SSL/TCP mux test on random port $PORT"
 
 ## Test connection via connection settings
-./qpid-perftest --count ${COUNT} --port ${PORT} -P ssl -b $TEST_HOSTNAME --summary || error "SSL connection failed!"
-./qpid-perftest --count ${COUNT} --port ${PORT} -P tcp -b $TEST_HOSTNAME --summary || error "TCP connection failed!"
+qpid-perftest --count ${COUNT} --port ${PORT} -P ssl -b $TEST_HOSTNAME --summary || error "SSL connection failed!"
+qpid-perftest --count ${COUNT} --port ${PORT} -P tcp -b $TEST_HOSTNAME --summary || error "TCP connection failed!"
 
 stop_brokers
 
@@ -271,67 +273,63 @@ if [[ !(-x $OPENSSL) ]] ; then
     exit 0
 fi
 
-if test -d $PYTHON_DIR; then
 ## verify python version > 2.5 (only 2.6+ does certificate checking)
-    PY_VERSION=$(python -c "import sys; print hex(sys.hexversion)")
-    if (( PY_VERSION < 0x02060000 )); then
-	echo >&2 "Detected python version < 2.6 - skipping certificate verification tests"
-	exit 0
-    fi
+PY_VERSION=$(python -c "import sys; print hex(sys.hexversion)")
+if (( PY_VERSION < 0x02060000 )); then
+    echo >&2 "Detected python version < 2.6 - skipping certificate verification tests"
+    exit 0
+fi
 
-    echo "Testing Certificate validation and Authentication with the Python Client..."
+echo "Testing Certificate validation and Authentication with the Python Client..."
 
 # extract the CA's certificate as a PEM file
-    get_ca_certs() {
-	$PK12UTIL -o ${TEST_CERT_DIR}/CA_pk12.out -d ${CERT_DB} -n "Test-CA"  -w ${CERT_PW_FILE} -k ${CERT_PW_FILE} > /dev/null
-	$OPENSSL pkcs12 -in ${TEST_CERT_DIR}/CA_pk12.out -out ${CA_PEM_FILE} -nokeys -passin file:${CERT_PW_FILE} >/dev/null
-	$PK12UTIL -o ${TEST_CERT_DIR}/other_CA_pk12.out -d ${OTHER_CA_CERT_DB} -n "Other-Test-CA" -w ${CERT_PW_FILE} -k ${CERT_PW_FILE} > /dev/null
-	$OPENSSL pkcs12 -in ${TEST_CERT_DIR}/other_CA_pk12.out -out ${OTHER_CA_PEM_FILE} -nokeys -passin file:${CERT_PW_FILE} >/dev/null
-    }
+get_ca_certs() {
+    $PK12UTIL -o ${TEST_CERT_DIR}/CA_pk12.out -d ${CERT_DB} -n "Test-CA"  -w ${CERT_PW_FILE} -k ${CERT_PW_FILE} > /dev/null
+    $OPENSSL pkcs12 -in ${TEST_CERT_DIR}/CA_pk12.out -out ${CA_PEM_FILE} -nokeys -passin file:${CERT_PW_FILE} >/dev/null
+    $PK12UTIL -o ${TEST_CERT_DIR}/other_CA_pk12.out -d ${OTHER_CA_CERT_DB} -n "Other-Test-CA" -w ${CERT_PW_FILE} -k ${CERT_PW_FILE} > /dev/null
+    $OPENSSL pkcs12 -in ${TEST_CERT_DIR}/other_CA_pk12.out -out ${OTHER_CA_PEM_FILE} -nokeys -passin file:${CERT_PW_FILE} >/dev/null
+}
 
-    get_ca_certs || error "Could not extract CA certificates as PEM files"
-    start_ssl_broker
-    PORT=${PORTS[0]}
-    URL=amqps://$TEST_HOSTNAME:$PORT
+get_ca_certs || error "Could not extract CA certificates as PEM files"
+start_ssl_broker
+PORT=${PORTS[0]}
+URL=amqps://$TEST_HOSTNAME:$PORT
 # verify the python client can authenticate the broker using the CA
-    if `${PY_PING_BROKER} -b $URL --ssl-trustfile=${CA_PEM_FILE}`; then echo "    Passed"; else { echo "    Failed"; exit 1; }; fi
+if `${PY_PING_BROKER} -b $URL --ssl-trustfile=${CA_PEM_FILE}`; then echo "    Passed"; else { echo "    Failed"; exit 1; }; fi
 # verify the python client fails to authenticate the broker when using the other CA
-    if `${PY_PING_BROKER} -b $URL --ssl-trustfile=${OTHER_CA_PEM_FILE} > /dev/null 2>&1`; then { echo "    Failed"; exit 1; }; else echo "    Passed"; fi
-    stop_brokers
+if `${PY_PING_BROKER} -b $URL --ssl-trustfile=${OTHER_CA_PEM_FILE} > /dev/null 2>&1`; then { echo "    Failed"; exit 1; }; else echo "    Passed"; fi
+stop_brokers
 
 # create a certificate without matching TEST_HOSTNAME, should fail to verify
 
-    create_certs "O=MyCo" "*.${TEST_HOSTNAME}.com" || error "Could not create server test certificate"
+create_certs "O=MyCo" "*.${TEST_HOSTNAME}.com" || error "Could not create server test certificate"
+get_ca_certs || error "Could not extract CA certificates as PEM files"
+start_ssl_broker
+PORT=${PORTS[0]}
+URL=amqps://$TEST_HOSTNAME:$PORT
+if `${PY_PING_BROKER} -b $URL --ssl-trustfile=${CA_PEM_FILE} > /dev/null 2>&1`; then { echo "    Failed"; exit 1; }; else echo "    Passed"; fi
+# but disabling the check for the hostname should pass
+if `${PY_PING_BROKER} -b $URL --ssl-trustfile=${CA_PEM_FILE} --ssl-skip-hostname-check`; then echo "    Passed"; else { echo "    Failed"; exit 1; }; fi
+stop_brokers
+
+# test SubjectAltName parsing
+
+if (( PY_VERSION >= 0x02070300 )); then
+# python 2.7.3+ supports SubjectAltName extraction
+# create a certificate with TEST_HOSTNAME only in SAN, should verify OK
+    create_certs "O=MyCo" "*.foo.com,${TEST_HOSTNAME},*xyz.com" || error "Could not create server test certificate"
     get_ca_certs || error "Could not extract CA certificates as PEM files"
     start_ssl_broker
     PORT=${PORTS[0]}
     URL=amqps://$TEST_HOSTNAME:$PORT
-    if `${PY_PING_BROKER} -b $URL --ssl-trustfile=${CA_PEM_FILE} > /dev/null 2>&1`; then { echo "    Failed"; exit 1; }; else echo "    Passed"; fi
-# but disabling the check for the hostname should pass
-    if `${PY_PING_BROKER} -b $URL --ssl-trustfile=${CA_PEM_FILE} --ssl-skip-hostname-check`; then echo "    Passed"; else { echo "    Failed"; exit 1; }; fi
+    if `${PY_PING_BROKER} -b $URL --ssl-trustfile=${CA_PEM_FILE}`; then echo "    Passed"; else { echo "    Failed"; exit 1; }; fi
     stop_brokers
 
-# test SubjectAltName parsing
-
-    if (( PY_VERSION >= 0x02070300 )); then
-    # python 2.7.3+ supports SubjectAltName extraction
-    # create a certificate with TEST_HOSTNAME only in SAN, should verify OK
-	create_certs "O=MyCo" "*.foo.com,${TEST_HOSTNAME},*xyz.com" || error "Could not create server test certificate"
-	get_ca_certs || error "Could not extract CA certificates as PEM files"
-	start_ssl_broker
-	PORT=${PORTS[0]}
-	URL=amqps://$TEST_HOSTNAME:$PORT
-	if `${PY_PING_BROKER} -b $URL --ssl-trustfile=${CA_PEM_FILE}`; then echo "    Passed"; else { echo "    Failed"; exit 1; }; fi
-	stop_brokers
-
-	create_certs "O=MyCo" "*${TEST_HOSTNAME}" || error "Could not create server test certificate"
-	get_ca_certs || error "Could not extract CA certificates as PEM files"
-	start_ssl_broker
-	PORT=${PORTS[0]}
-	URL=amqps://$TEST_HOSTNAME:$PORT
-	if `${PY_PING_BROKER} -b $URL --ssl-trustfile=${CA_PEM_FILE}`; then echo "    Passed"; else { echo "    Failed"; exit 1; }; fi
-	stop_brokers
-    fi
-
+    create_certs "O=MyCo" "*${TEST_HOSTNAME}" || error "Could not create server test certificate"
+    get_ca_certs || error "Could not extract CA certificates as PEM files"
+    start_ssl_broker
+    PORT=${PORTS[0]}
+    URL=amqps://$TEST_HOSTNAME:$PORT
+    if `${PY_PING_BROKER} -b $URL --ssl-trustfile=${CA_PEM_FILE}`; then echo "    Passed"; else { echo "    Failed"; exit 1; }; fi
+    stop_brokers
 fi
-
