Merge from trunk tag to-cmake-25mar09 (r758432)
git-svn-id: https://svn.apache.org/repos/asf/qpid/branches/cmake@758465 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/qpid/cpp/src/tests/federated_cluster_test b/qpid/cpp/src/tests/federated_cluster_test
--- a/qpid/cpp/src/tests/federated_cluster_test
+++ b/qpid/cpp/src/tests/federated_cluster_test
@@ -21,8 +21,8 @@
 
 # Test reliability of the replication feature in the face of link
 # failures:
-MY_DIR=`dirname \`which $0\``
-PYTHON_DIR=${MY_DIR}/../../../python
+srcdir=`dirname $0`
+PYTHON_DIR=$srcdir/../../../python
 
 trap stop_brokers EXIT
 
@@ -37,9 +37,14 @@ stop_brokers() {
         unset BROKER_A
     fi      
     if [[ $NODE_1 ]] ; then
-        ./stop_cluster
+        ../qpidd -q --port $NODE_1
         unset NODE_1
     fi
+    if [[ $NODE_2 ]] ; then
+        ../qpidd -q --port $NODE_2
+        unset NODE_2
+    fi
+    rm cluster.ports
 }
 
 start_brokers() {
@@ -48,19 +53,20 @@ start_brokers() {
     BROKER_A=`cat fed.port.tmp`
 
     #...and start cluster
-    ./start_cluster 2 || fail "Could not start cluster"
+    $srcdir/start_cluster 2 || fail "Could not start cluster"
     NODE_1=$(head -1 cluster.ports)
     NODE_2=$(tail -1 cluster.ports)
 }
 
 setup() {
+    export PYTHONPATH=$PYTHON_DIR
     #create exchange on both cluster and single broker
     $PYTHON_DIR/commands/qpid-config -a "localhost:$BROKER_A" add exchange direct test-exchange
     $PYTHON_DIR/commands/qpid-config -a "localhost:$NODE_1" add exchange direct test-exchange
 
     #create dynamic routes for test exchange
-    $PYTHON_DIR/commands/qpid-route dynamic add "localhost:$NODE_1" "localhost:$BROKER_A" test-exchange
-    $PYTHON_DIR/commands/qpid-route dynamic add "localhost:$BROKER_A" "localhost:$NODE_1" test-exchange
+    $PYTHON_DIR/commands/qpid-route dynamic add "localhost:$NODE_2" "localhost:$BROKER_A" test-exchange
+    $PYTHON_DIR/commands/qpid-route dynamic add "localhost:$BROKER_A" "localhost:$NODE_2" test-exchange
 
     #create test queue on cluster and bind it to the test exchange
     $PYTHON_DIR/commands/qpid-config -a "localhost:$NODE_1" add queue test-queue
@@ -71,7 +77,7 @@ setup() {
     $PYTHON_DIR/commands/qpid-config -a "localhost:$BROKER_A" bind test-exchange test-queue from-cluster
 }
 
-run_test_pull_to_cluster() {
+run_test_pull_to_cluster_two_consumers() {
     #start consumers on each of the two nodes of the cluster
     ./receiver --port $NODE_1 --queue test-queue --credit-window 1 > fed1.out.tmp &
     ./receiver --port $NODE_2 --queue test-queue --credit-window 1 > fed2.out.tmp &
@@ -83,6 +89,20 @@ run_test_pull_to_cluster() {
     #combine output of the two consumers, sort it and compare with the expected stream
     wait
     sort -g -k 2 fed1.out.tmp fed2.out.tmp > fed.out.tmp
+    diff fed.in.tmp fed.out.tmp || fail "federated link to cluster failed: expectations not met!"
+        
+    rm -f fed*.tmp #cleanup
+}
+
+run_test_pull_to_cluster() {
+    #send stream of messages to test exchange on single broker
+    for i in `seq 1 1000`; do echo Message $i >> fed.in.tmp; done
+    ./sender --port $BROKER_A --exchange test-exchange --routing-key to-cluster --send-eos 1 < fed.in.tmp
+
+    #consume from remaining node of the cluster
+    ./receiver --port $NODE_2 --queue test-queue > fed.out.tmp
+
+    #verify all messages are received
     diff fed.in.tmp fed.out.tmp || fail "federated link to cluster failed: expectations not met!"
         
     rm -f fed*.tmp #cleanup
@@ -124,8 +144,19 @@ EOF
     echo "brokers started"
     setup
     echo "setup completed"
-    run_test_pull_to_cluster    
+    run_test_pull_to_cluster_two_consumers    
     echo "federated link to cluster verified"
     run_test_pull_from_cluster    
     echo "federated link from cluster verified"
+    if [[ $TEST_NODE_FAILURE ]] ; then
+        #kill first cluster node and retest
+        kill -9 $(../qpidd --check --port $NODE_1) && unset NODE_1
+        echo "killed first cluster node; waiting for links to re-establish themselves..."
+        sleep 5
+        echo "retesting..."
+        run_test_pull_to_cluster
+        echo "federated link to cluster verified"
+        run_test_pull_from_cluster    
+        echo "federated link from cluster verified"    
+    fi
 fi
diff --git a/qpid/cpp/src/tests/replication_test b/qpid/cpp/src/tests/replication_test
--- a/qpid/cpp/src/tests/replication_test
+++ b/qpid/cpp/src/tests/replication_test
@@ -22,21 +22,20 @@
 # Run a test of the replication feature
 MY_DIR=`dirname \`which $0\``
 PYTHON_DIR=${MY_DIR}/../../../python
-
 trap stop_brokers INT TERM QUIT
 
 stop_brokers() {
-    if [[ $BROKER_A ]] ; then
+    if [ x$BROKER_A != x ]; then
         ../qpidd -q --port $BROKER_A
         unset BROKER_A
     fi      
-    if [[ $BROKER_B ]] ; then
+    if [ x$BROKER_B != x ]; then
         ../qpidd -q --port $BROKER_B
         unset BROKER_B
     fi
 }
 
-if test -d ${PYTHON_DIR} && test -e ../.libs/replicating_listener.so && test -e ../.libs/replication_exchange.so ;  then
+if test -d ${PYTHON_DIR} && test -f ../.libs/replicating_listener.so && test -f ../.libs/replication_exchange.so;  then
     rm -f queue-*.repl replication-*.log #cleanup from any earlier runs
 
     ../qpidd --daemon --port 0 --no-data-dir --no-module-dir --auth no --load-module ../.libs/replicating_listener.so --replication-queue replication --create-replication-queue true  --log-enable info+ --log-to-file replication-source.log  --log-to-stderr 0 > qpidd.port
@@ -44,7 +43,8 @@ if test -d ${PYTHON_DIR} && test -e ../.libs/replicating_listener.so && test -e 
 
     ../qpidd --daemon --port 0 --no-data-dir --no-module-dir --auth no --load-module ../.libs/replication_exchange.so  --log-enable info+ --log-to-file replication-dest.log  --log-to-stderr 0 > qpidd.port
     BROKER_B=`cat qpidd.port`
-    export PYTHONPATH=$PYTHON_DIR
+    PYTHONPATH=$PYTHON_DIR
+    export PYTHONPATH
     echo "Running replication test between localhost:$BROKER_A and localhost:$BROKER_B"
 
     $PYTHON_DIR/commands/qpid-config -a "localhost:$BROKER_B" add exchange replication replication
@@ -55,23 +55,39 @@ if test -d ${PYTHON_DIR} && test -e ../.libs/replicating_listener.so && test -e 
     $PYTHON_DIR/commands/qpid-config -a "localhost:$BROKER_A" add queue queue-a --generate-queue-events 2
     $PYTHON_DIR/commands/qpid-config -a "localhost:$BROKER_A" add queue queue-b --generate-queue-events 2
     $PYTHON_DIR/commands/qpid-config -a "localhost:$BROKER_A" add queue queue-c --generate-queue-events 1
+    $PYTHON_DIR/commands/qpid-config -a "localhost:$BROKER_A" add queue queue-d --generate-queue-events 2
 
     $PYTHON_DIR/commands/qpid-config -a "localhost:$BROKER_B" add queue queue-a
     $PYTHON_DIR/commands/qpid-config -a "localhost:$BROKER_B" add queue queue-b
     $PYTHON_DIR/commands/qpid-config -a "localhost:$BROKER_B" add queue queue-c
+    #queue-d deliberately not declared on DR; this error case should be handled
 
-    #publish and consume from test queus on broker A:
-    for i in `seq 1 10`; do echo Message $i for A >> queue-a-input.repl; done
-    for i in `seq 1 20`; do echo Message $i for B >> queue-b-input.repl; done
-    for i in `seq 1 15`; do echo Message $i for C >> queue-c-input.repl; done
+    #publish and consume from test queues on broker A:
+    i=1
+    while [ $i -le 10 ]; do
+        echo Message $i for A >> queue-a-input.repl
+        i=`expr $i + 1`
+    done
+    i=1
+    while [ $i -le 20 ]; do
+        echo Message $i for B >> queue-b-input.repl 
+        i=`expr $i + 1`
+    done
+    i=1
+    while [ $i -le 15 ]; do
+        echo Message $i for C >> queue-c-input.repl 
+        i=`expr $i + 1`
+    done
 
     ./sender --port $BROKER_A --routing-key queue-a --send-eos 1 < queue-a-input.repl
     ./sender --port $BROKER_A --routing-key queue-b --send-eos 1 < queue-b-input.repl
     ./sender --port $BROKER_A --routing-key queue-c --send-eos 1 < queue-c-input.repl
+    echo dummy | ./sender --port $BROKER_A --routing-key queue-d --send-eos 1
 
     ./receiver --port $BROKER_A --queue queue-a --messages 5 > /dev/null 
     ./receiver --port $BROKER_A --queue queue-b --messages 10 > /dev/null
     ./receiver --port $BROKER_A --queue queue-c --messages 10 > /dev/null
+    ./receiver --port $BROKER_A --queue queue-d > /dev/null
     
     #shutdown broker A then check that broker Bs versions of the queues are as expected
     ../qpidd -q --port $BROKER_A
@@ -90,7 +106,9 @@ if test -d ${PYTHON_DIR} && test -e ../.libs/replicating_listener.so && test -e 
     diff queue-b-backup.repl queue-b-expected.repl || FAIL=1
     diff queue-c-backup.repl queue-c-input.repl || FAIL=1
 
-    if [[ $FAIL ]]; then
+    grep 'queue-d does not exist' replication-dest.log > /dev/null || echo "WARNING: Expected error to be logged!"
+
+    if [ x$FAIL != x ]; then
         echo replication test failed: expectations not met!
         exit 1
     else 
