fixed the cpp/python test integration
git-svn-id: https://svn.apache.org/repos/asf/qpid/trunk@803270 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/qpid/cpp/src/tests/python_tests b/qpid/cpp/src/tests/python_tests
--- a/qpid/cpp/src/tests/python_tests
+++ b/qpid/cpp/src/tests/python_tests
@@ -23,12 +23,11 @@
 QPID_PORT=${QPID_PORT:-5672}
 PYTHON_TESTS=${PYTHON_TESTS:-$*}
 QPID_PYTHON_DIR=${QPID_PYTHON_DIR:-`dirname $0`/../../../python}
-SPEC=${SPEC:-0-10-errata}
-FAILING=${FAILING:-cpp_failing_0-10.txt}
+FAILING=${FAILING:-/dev/null}
 
-if test -d $QPID_PYTHON_DIR; then 
+if test -d $QPID_PYTHON_DIR; then
     cd $QPID_PYTHON_DIR
-    ./run-tests --skip-self-test -v -s $SPEC -I $FAILING -b localhost:$QPID_PORT $PYTHON_TESTS || { echo "FAIL python tests for $SPEC"; exit 1; }
+    ./qpid-python-test -b localhost:$QPID_PORT -I $FAILING $PYTHON_TESTS || { echo "FAIL python tests"; exit 1; }
 else
     echo "WARNING: No python tests. $QPID_PYTHON_DIR not found."
 fi
