Merge in trunk to r752275
git-svn-id: https://svn.apache.org/repos/asf/qpid/branches/qpid-1673@752300 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/qpid/cpp/src/tests/replication_test b/qpid/cpp/src/tests/replication_test
--- a/qpid/cpp/src/tests/replication_test
+++ b/qpid/cpp/src/tests/replication_test
@@ -55,10 +55,12 @@ if test -d ${PYTHON_DIR} && test -e ../.libs/replicating_listener.so && test -e 
     $PYTHON_DIR/commands/qpid-config -a "localhost:$BROKER_A" add queue queue-a --generate-queue-events 2
     $PYTHON_DIR/commands/qpid-config -a "localhost:$BROKER_A" add queue queue-b --generate-queue-events 2
     $PYTHON_DIR/commands/qpid-config -a "localhost:$BROKER_A" add queue queue-c --generate-queue-events 1
+    $PYTHON_DIR/commands/qpid-config -a "localhost:$BROKER_A" add queue queue-d --generate-queue-events 2
 
     $PYTHON_DIR/commands/qpid-config -a "localhost:$BROKER_B" add queue queue-a
     $PYTHON_DIR/commands/qpid-config -a "localhost:$BROKER_B" add queue queue-b
     $PYTHON_DIR/commands/qpid-config -a "localhost:$BROKER_B" add queue queue-c
+    #queue-d deliberately not declared on DR; this error case should be handled
 
     #publish and consume from test queus on broker A:
     for i in `seq 1 10`; do echo Message $i for A >> queue-a-input.repl; done
@@ -68,10 +70,12 @@ if test -d ${PYTHON_DIR} && test -e ../.libs/replicating_listener.so && test -e 
     ./sender --port $BROKER_A --routing-key queue-a --send-eos 1 < queue-a-input.repl
     ./sender --port $BROKER_A --routing-key queue-b --send-eos 1 < queue-b-input.repl
     ./sender --port $BROKER_A --routing-key queue-c --send-eos 1 < queue-c-input.repl
+    echo dummy | ./sender --port $BROKER_A --routing-key queue-d --send-eos 1
 
     ./receiver --port $BROKER_A --queue queue-a --messages 5 > /dev/null 
     ./receiver --port $BROKER_A --queue queue-b --messages 10 > /dev/null
     ./receiver --port $BROKER_A --queue queue-c --messages 10 > /dev/null
+    ./receiver --port $BROKER_A --queue queue-d > /dev/null
     
     #shutdown broker A then check that broker Bs versions of the queues are as expected
     ../qpidd -q --port $BROKER_A
@@ -89,6 +93,8 @@ if test -d ${PYTHON_DIR} && test -e ../.libs/replicating_listener.so && test -e 
     diff queue-a-backup.repl queue-a-expected.repl || FAIL=1
     diff queue-b-backup.repl queue-b-expected.repl || FAIL=1
     diff queue-c-backup.repl queue-c-input.repl || FAIL=1
+
+    grep 'queue-d does not exist' replication-dest.log > /dev/null || echo "WARNING: Expected error to be logged!"
 
     if [[ $FAIL ]]; then
         echo replication test failed: expectations not met!
