Align run_test shell and Powershell versions. Changes the option syntax from two-hyphen to one. Fixes QPID-6399.
git-svn-id: https://svn.apache.org/repos/asf/qpid/trunk@1667349 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/qpid/cpp/src/tests/run_test b/qpid/cpp/src/tests/run_test
--- a/qpid/cpp/src/tests/run_test
+++ b/qpid/cpp/src/tests/run_test
@@ -34,17 +34,17 @@
 wrapper="Qpid Test Wrapper"
 function usage {
   echo "Usage:"
-  echo " --working-dir DIR"
-  echo " --build-dir DIR"
-  echo " --source-dir DIR"
-  echo " --python       - run python script"
-  echo " --boost-test   - run boost unit test"
-  echo " --xml          - XML output from tests"
-  echo " --start-broker - start/stop broker before/after test"
-  echo " --broker-options - use these extra options when starting broker"
-  echo " --help           - print this message"
-  echo " --             - This is required to separate the wrapped command"
-  echo "                  from the test parameters"
+  echo " -workingDir DIR"
+  echo " -buildDir DIR"
+  echo " -sourceDir DIR"
+  echo " -python       - run python script"
+  echo " -boostTest   - run boost unit test"
+  echo " -xml          - XML output from tests"
+  echo " -startBroker - start/stop broker before/after test"
+  echo " -brokerOptions - use these extra options when starting broker"
+  echo " -help           - print this message"
+  echo " --            - This is required to separate the wrapped command"
+  echo "                 from the test parameters"
 }
 
 function illegal_option {
@@ -66,21 +66,21 @@ working_dir='.'
 while true; do
 case "$1" in
     --)                                  shift; break ;;
-    # Split up any parameters expressed as --blah=foo
+    # Split up any parameters expressed as -blah=foo
     # and process them next time round the loop
-    --*=*)            option=${1%%=*}; param=${1#*=}
+    -*=*)             option=${1%%=*}; param=${1#*=}
                       shift;
                       set -- "$option" "$param" "$@"  ;;
-    --working-dir)    working_dir=$2;    shift 2      ;;
-    --build-dir)      build_dir=$2;      shift 2      ;;
-    --source-dir)     source_dir=$2;     shift 2      ;;
-    --python)         run_python=yes;    shift        ;;
-    --boost-test)     boost_test=yes;    shift        ;;
-    --xml)            xml_output=yes;    shift        ;;
-    --start-broker)   start_broker=yes;  shift        ;;
-    --broker-options) qpidd_extra_options=$2; shift 2 ;;
-    --help)           usage;             exit 0;      ;;
-    --*)              illegal_option "$1"; exit 1;    ;;
+    -workingDir)      working_dir=$2;    shift 2      ;;
+    -buildDir)        build_dir=$2;      shift 2      ;;
+    -sourceDir)       source_dir=$2;     shift 2      ;;
+    -python)          run_python=yes;    shift        ;;
+    -boostTest)       boost_test=yes;    shift        ;;
+    -xml)             xml_output=yes;    shift        ;;
+    -startBroker)     start_broker=yes;  shift        ;;
+    -brokerOptions)   qpidd_extra_options=$2; shift 2 ;;
+    -help)            usage;             exit 0;      ;;
+    -*)               illegal_option "$1"; exit 1;    ;;
     '')               no_command;        exit 1;      ;;
     *)                ignored_argument "$1"; shift;   ;;
 esac
