QPID-1198: (Partial) Fix test shell scripts to work with /bin/sh Patches from Manuel Teira. These scripts have #!/bin/sh but they were previously really dependent on bash.
git-svn-id: https://svn.apache.org/repos/asf/incubator/qpid/trunk@680826 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/qpid/cpp/src/tests/run_federation_tests b/qpid/cpp/src/tests/run_federation_tests
--- a/qpid/cpp/src/tests/run_federation_tests
+++ b/qpid/cpp/src/tests/run_federation_tests
@@ -1,9 +1,9 @@
 #!/bin/sh
 # Run the federation tests.
-MY_DIR=$(dirname $(which $0))
+MY_DIR=`dirname \`which $0\``
 PYTHON_DIR=${MY_DIR}/../../../python
 
-trap stop_brokers EXIT
+trap stop_brokers INT TERM QUIT
 
 start_brokers() {
     ../qpidd --daemon --port 0 --no-data-dir --no-module-dir --auth no > qpidd.port
@@ -20,7 +20,13 @@ stop_brokers() {
 if test -d ${PYTHON_DIR} ;  then
     start_brokers
     echo "Running federation tests using brokers on ports $LOCAL_PORT $REMOTE_PORT"
-    export PYTHONPATH=${PYTHON_DIR}
-    ${MY_DIR}/federation.py -v -s ${MY_DIR}/../../../specs/amqp.0-10-qpid-errata.xml -b localhost:$LOCAL_PORT --remote-port $REMOTE_PORT  || { echo "FAIL federation tests"; exit 1; }
+    PYTHONPATH=${PYTHON_DIR}
+    export PYTHONPATH
+    ${MY_DIR}/federation.py -v -s ${MY_DIR}/../../../specs/amqp.0-10-qpid-errata.xml -b localhost:$LOCAL_PORT --remote-port $REMOTE_PORT
+    RETCODE=$?
+    stop_brokers
+    if test x$RETCODE != x0; then 
+        echo "FAIL federation tests"; exit 1;
+    fi
 fi
 
