QPID-5711: HA cannot promote primary if SASL security is enabled.
Updated the qpid-ha tool and qpidd init scripts to handle SASL authentication.
The qpid-ha script as as called by the qpidd-primary init script now reads
authentication settings from the qpidd.conf file and uses them to connect to the local broker.

- qpidd-primary script respects prefix: use installed location for qpidd script, not "service" call
- qpid-ha added --config option qpid-ha options to use qpidd.conf for local broker connection.
- qpid-ha --all use user/pass for each broker.

git-svn-id: https://svn.apache.org/repos/asf/qpid/trunk@1589391 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/qpid/cpp/etc/qpidd-primary.in b/qpid/cpp/etc/qpidd-primary.in
--- a/qpid/cpp/etc/qpidd-primary.in
+++ b/qpid/cpp/etc/qpidd-primary.in
@@ -37,27 +37,28 @@
 
 prog=qpidd
 
-# Source function library.
-. /etc/rc.d/init.d/functions
-
-if [ -f @sysconfdir@/sysconfig/$prog ] ; then
-    . @sysconfdir@/sysconfig/$prog
-fi
-
 # The following variables can be overridden in @sysconfdir@/sysconfig/$prog
-[[ $QPID_PORT ]] || QPID_PORT=5672
-[[ $QPID_HA ]]   || QPID_HA=@bindir@/qpid-ha
-export QPID_PORT
+QPID_INIT=@initdir@/$prog
+QPID_CONFIG=@confdir@/qpidd.conf
+QPID_HA=@bindir@/qpid-ha
+QPID_HA_OPTIONS="--config $QPID_CONFIG"
+
+# Source configuration
+test -f @sysconfdir@/sysconfig/$prog && source @sysconfdir@/sysconfig/$prog
+
+# Check presence of executables/scripts
+for f in $QPID_INIT $QPID_HA; do
+    test -x $f || { echo "$f not found or not executable"; exit 5; }
+done
+
+QPID_HA="$QPID_HA $QPID_HA_OPTIONS"
+
+source /etc/rc.d/init.d/functions
 
 RETVAL=0
 
-#ensure binary is present and executable
-if [[ !(-x $QPID_HA) ]]; then
-    echo "qpid-ha executable not found or not executable"
-fi
-
 status() {
-    if $QPID_HA -b localhost:$QPID_PORT status --is-primary ; then
+    if $QPID_HA status --is-primary ; then
 	echo "qpidd is primary"
     else
 	echo "qpidd is not primary"
@@ -66,14 +67,14 @@ status() {
 }
 
 start() {
-    service qpidd start
+    $QPID_INIT start
     echo -n $"Promoting qpid daemon to cluster primary: "
-    $QPID_HA -b localhost:$QPID_PORT promote
+    $QPID_HA promote
     [ "$?" -eq 0 ] && success || failure
 }
 
 stop() {
-    service qpidd stop
+    $QPID_INIT stop
 }
 
 reload() {
@@ -82,7 +83,7 @@ reload() {
 }
 
 restart() {
-    service qpidd restart && start
+    $QPID_INIT restart && start
 }
 
 # See how we were called.
